apiVersion: v1
kind: Service
metadata:
  name: {{ include "fridayapp.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "fridayapp.name" . }}
    helm.sh/chart: {{ include "fridayapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort:  {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fridayapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
