  - name: get fly
    unarchive:
      src: https://github.com/concourse/concourse/releases/download/v5.3.0/fly-5.3.0-linux-amd64.tgz
      remote_src: yes
      dest: /usr/local/bin/
      creates: /usr/local/bin/fly
      mode: 0755

  - name: read kube config  
    include_vars:
      file: /home/vagrant/.kube/config
      name: kubeconf
  
  - shell: cat /home/vagrant/.minikube/ca.crt | base64 | tr -d '\n'
    register: cluster_ca

  - shell: kubectl get secret $(kubectl get serviceaccount default -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.token}'
    register: cluster_token
  
  - shell: cat /home/vagrant/.minikube/client.key | base64 | tr -d '\n'
    register: admin_key

  - shell: cat /home/vagrant/.minikube/client.crt | base64 | tr -d '\n'
    register: admin_cert
  
  - name: add cluster url
    lineinfile:
      path: /home/vagrant/nydemo/ci/credentials.yaml
      regexp: '^cluster_url:'
      line: "cluster_url: {{ kubeconf.clusters.0.cluster.server }}"
      
  - name: add cluster ca
    lineinfile:
      path: /home/vagrant/nydemo/ci/credentials.yaml
      regexp: '^cluster_ca:'
      line: "cluster_ca: {{ cluster_ca.stdout }}"
      
  - name: add cluster token
    lineinfile:
      path: /home/vagrant/nydemo/ci/credentials.yaml
      regexp: '^cluster_token:'
      line: "cluster_token: {{ cluster_token.stdout }}"

  - name: add admin key
    lineinfile:
      path: /home/vagrant/nydemo/ci/credentials.yaml
      regexp: '^admin_key:'
      line: "admin_key: {{ admin_key.stdout }}"

  - name: add admin_cert
    lineinfile:
      path: /home/vagrant/nydemo/ci/credentials.yaml
      regexp: '^admin_cert:'
      line: "admin_cert: {{ admin_cert.stdout }}"
  
  - name: wait for concourse
    wait_for:
      host: 127.0.0.1
      port: 31155
      delay: 10
      timeout: 600

  - name: create and start pipeline
    shell: >
      fly login -t nydemo -u test -p test -c http://minikube:31155 &&
      fly -t nydemo set-pipeline -p nydemo -c pipeline.yaml --load-vars-from=credentials.yaml --non-interactive &&
      fly -t nydemo unpause-pipeline -p nydemo
    args:
      chdir: /home/vagrant/nydemo/ci
