  ## restart minikube under /home/vagrant
  
  - name: start minikube from vagrant home
    become: yes
    become_user: vagrant
    command: >
      sudo /usr/local/bin/minikube start --vm-driver none 
      --memory 7168 --cpus 2
      --extra-config=kubelet.EvictionSoft="memory.available<500Mi,nodefs.available<1Gi,imagefs.available<1Gi" 
      --extra-config=kubelet.EvictionHard="memory.available<300Mi,nodefs.available<600Mi,imagefs.available<600Mi" 
      --extra-config=kubelet.EvictionMinimumReclaim="memory.available=150Mi,nodefs.available=300Mi,imagefs.available=300Mi" 
      --extra-config=kubelet.EvictionSoftGracePeriod="memory.available=2m,nodefs.available=2m,imagefs.available=2m" 
      --extra-config=kubelet.EvictionMaxPodGracePeriod="60"
    args:
      chdir: /home/vagrant
      warn: false

  ## Wait for minikube to actually start
  ## For real world cases proper checks should be used, for demo it's enough
  - name: waiting
    command: sleep 120
